image: alpine:latest

pages:
  stage: deploy
  script:
  - echo "Moving files to public folder..."
  - mkdir public
  - cp -vvv -rap ./* public/
  artifacts:
    paths:
    - public
  only:
  - master
